opt_out_usage
default_platform :ios

platform :ios do

  desc 'Run unit tests'
  lane :test do
    system('pkill', '-9', '-x', 'Simulator')
    UI.success('Simulator app killed')

    device = ENV['TEST_DEVICE_NAME'] || 'iPhone 6s'
    UI.message("Simulator testing device set to '#{device}'")

    build_directory = 'build'
    output_directory = build_directory + '/tests'

    scan(
      :workspace => 'HubFramework.xcworkspace',
      :scheme => 'HubFramework',
      :devices => [device],
      :derived_data_path => build_directory + '/DerivedData',
      :output_directory => output_directory,
      :buildlog_path => build_directory + '/logs/tests',
      :code_coverage => true,
      :output_types => '',
      :fail_build => false,
    )

    trainer(
      path: build_directory,
      output_directory: output_directory,
      extension: '.junit'
    )

    codecov() if ENV['CODECOV_TOKEN'] or ENV['TRAVIS'] == 'true'
  end


  desc 'Build the demo app'
  lane :demo do
    xcodebuild(
      :build => true,
      :parallelize_targets => true,
      :project => 'demo/HubFrameworkDemo.xcodeproj',
      :target => 'HubFrameworkDemo',
      :sdk => 'iphonesimulator',
      :configuration => 'Release',
      :derivedDataPath => 'build/DerivedData',
      :buildlog_path => 'build/logs/demo',
    )
  end


  desc 'Lint the source code and other linteable artifacts'
  lane :lint do
    pod_lib_lint(:quick => true)

    license_header_files = Dir.chdir("..") do
      license_header_files = Dir.glob('{demo/sources/*.swift,include/HubFramework/*.h,sources/*.{h,m},tests/*/*.{h,m},tests/*.m}')
    end
    lint_sources_for_license_header(
      :template => 'other/license_header_template.txt',
      :files => license_header_files
    )
  end

  desc 'Validate changes according to a set of rules'
  lane :validate_changes do
    danger
  end


  desc 'Update the framework documentation and publish it'
  lane :update_docs do
    if git_branch == "master"
      # sh 'cd .. && rake docs:generate'
      # sh 'cd .. && rake docs:publish'
    end
  end


  desc 'Execute all CI lanes'
  desc 'This action can be configured using the following environment variable (valid values are `YES` and `NO`):'
  desc ''
  desc '- `LINT`:           Whether the sources and certain artifacts should be linted defaults to `YES`'
  desc '- `RUN_TESTS`:      Whether unit tests should be run, defaults to `YES`'
  desc '- `BUILD_DEMO_APP`: Whether the demo app should be built or not, defaults to `YES`'
  lane :ci_all do
    lint unless shouldSkipStep('LINT')
    test unless shouldSkipStep('RUN_TESTS')
    demo unless shouldSkipStep('BUILD_DEMO_APP')
  end

  # Whether we should execute the step or not.
  # Looks up the value in the environment variables where a missing, empty, or 'YES' string is
  # considerered to denote that the step should be ran. Any other value is interpreted as 'skip
  # this step'.
  def shouldSkipStep(step)
    value = ENV[step].to_s

    # We should skip if the value isn't the empty string, or if it's set to something other than YES
    not value.empty? and value != 'YES'
  end

end
