opt_out_usage
default_platform :ios

platform :ios do

  desc 'Run unit tests'
  lane :test do
    system('pkill', '-9', '-x', 'Simulator')
    UI.success('Simulator app killed')

    device = ENV['TEST_DEVICE_NAME'] || 'iPhone 6s'
    UI.message("Simulator testing device set to '#{device}'")

    build_directory = 'build'
    output_directory = build_directory + '/tests'

    scan(
      :workspace => 'HubFramework.xcworkspace',
      :scheme => 'HubFramework',
      :devices => [device],
      :derived_data_path => build_directory + '/DerivedData',
      :output_directory => output_directory,
      :buildlog_path => build_directory + '/logs/tests',
      :code_coverage => true,
      :output_types => '',
      :fail_build => false,
    )

    trainer(
      path: build_directory,
      output_directory: output_directory,
      extension: '.junit'
    )

    codecov() if ENV['CODECOV_TOKEN'] or ENV['TRAVIS'] == 'true'
  end


  desc 'Build the demo app'
  lane :demo do
    xcodebuild(
      :build => true,
      :parallelize_targets => true,
      :project => 'demo/HubFrameworkDemo.xcodeproj',
      :target => 'HubFrameworkDemo',
      :sdk => 'iphonesimulator',
      :configuration => 'Release',
      :derived_data_path => 'build/DerivedData',
      :buildlog_path => 'build/logs/demo',
    )
  end


  desc 'Lint the source code and other linteable artifacts'
  lane :lint do
    pod_lib_lint(:quick => true)

    license_header_files = Dir.chdir("..") do
      license_header_files = Dir.glob('{demo/sources/*.swift,include/HubFramework/*.h,sources/*.{h,m},tests/*/*.{h,m},tests/*.m}')
    end
    lint_sources_for_license_header(
      :template => 'other/license_header_template.txt',
      :files => license_header_files
    )
  end

  desc 'Validate changes according to a set of rules'
  lane :validate_changes do
    danger
  end


  desc 'Update documentation and publish them'
  lane :update_docs do
    if git_branch == "master"
      # sh 'cd .. && rake docs:generate'
      # sh 'cd .. && rake docs:publish'
    end
  end

end
